version: '3.9'


networks:
  demo:
    driver: bridge

services:

  redis:
    image: redis:7.2.3
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - demo

  api-1:
    build:
      context: ./Demo.API
      dockerfile: Dockerfile
    image: technobre/demo-api:latest
    container_name: api-1
    ports:
      - 8081:80
    environment:
      CONNECTIONSTRINGS__REDIS: redis:6379
    networks:
      - demo
    depends_on:
      - redis

  api-2:
    build:
      context: ./Demo.API
      dockerfile: Dockerfile
    image: technobre/demo-api:latest
    container_name: api-2
    ports:
      - 8082:80
    environment:
      CONNECTIONSTRINGS__REDIS: redis:6379
    networks:
      - demo
    depends_on:
      - redis


  nginx:
    image: nginx:1.25.3
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Demo.WebClient/:/var/www/html
    networks:
      - demo
    depends_on:
      - api-1
      - api-2
